name: dart_server_httpd
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

dependencies:
  args: any
  shelf: any
  shelf_router: any
  shelf_static: any

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0

executables:
  dart_server_httpd: